# -*- coding: utf-8 -*-
"""TASK 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15JqC6Ui7z1YDD9M99L8ptzFngJXCU9xr

## **Task-2 : UNEMPLOYMENT ANALYSIS WITH PYTHON**

## **Name: Mrudav Pranav Patel**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

df=pd.read_csv("/content/Unemployment_Rate_upto_11_2020.csv")

df.head(100)

#Checking for missing values
df.isnull().sum()

#Description of dataset
df.describe()

#correlation between the features of this dataset
df.corr()

#visual representation of correlation between the features of this dataset

plt.style.use('seaborn-whitegrid')
plt.figure(figsize=(14, 12))
sns.heatmap(df.corr())
plt.show()

#unemployment rate according to different regions of India
df.columns= ["States","Date","Frequency",
               "Estimated Unemployment Rate","Estimated Employed",
               "Estimated Labour Participation Rate","Region",
               "longitude","latitude"]

plt.figure(figsize=(10, 8))
plt.title("Indian Unemployment")
sns.histplot(x="Estimated Unemployment Rate", hue="Region", data=df)
plt.show()

sns.pairplot(df)

unemploment = df[["States", "Region", "Estimated Unemployment Rate"]]
figure = px.sunburst(unemploment, path=["Region", "States"], 
                     values="Estimated Unemployment Rate", 
                     width=500, height=500, color_continuous_scale="RdY1Gn", 
                     title="Unemployment Rate in India")
figure.show()

